name: lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run Bootstrap
      run: npm run bootstrap
    - name: Build Type
      run: npm run build:type
    - name: Run ESLint
      run:  npm run lint
    - name: Create Status Check
      run: gh api "repos/:owner/:repo/statuses/$GITHUB_SHA" -X POST -F "state=success" -F "description=All checks passed"